### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by andre2007** [night-shift/fpconv#2]
Hello night-shift,
the D Programming Language (dlang.org) is missing an implementation for converting floating point numbers to strings. At the moment a C function is called which has the big disadvantage that the conversion cannot be done at compile time.
(D has extremely good compile time and template features)
It would be genius if we could add your implementation to the D standard library.
This would solve a lot of problems we currently have.

The issue is, D is using the Boost license (https://www.boost.org/LICENSE_1_0.txt).
Boost and MIT license are not compatible. 
Is there any chance you could publish your implementation also under the Boost license?

Please see also this forum post about your implementation 
https://forum.dlang.org/thread/pfnyycxolnrlxtgzimgp@forum.dlang.org

Kind regards
Andre

**Comment by night-shift** [comment]
Hi Andre,

license is now updated. 

Cheers,

**Comment by andre2007** [comment]
Thank you sooo much!
That is fantastic. 

Kind regards 
Andre
